# Generated by Django 3.1.7 on 2021-03-28 04:40

from django.db import migrations


def copy_src_to_dst(source_class, destination_class):
    for src in source_class.objects.all():
        dst = destination_class(title=src.title,
                                start=src.start,
                                description=src.description,
                                slots=src.slots,
                                )
        dst.save()
        dst.speakers.set(src.speakers.all())
        src.delete()

def forward_course_abc_to_mti(apps, schema_editor):
    copy_src_to_dst(apps.get_model('core', 'CourseOld'),
                    apps.get_model('core', 'Course')
                    )


def backward_course_abc_to_mti(apps, schema_editor):
    copy_src_to_dst(apps.get_model('core', 'CourseOld'),
                    apps.get_model('core', 'Course')
                    )

class Migration(migrations.Migration):
    """
    - For each course ABC (Abstract Base Class), instanciate an MTI (Multi Table Inheritance
    - Save MTI
    - Associate speakers from ABC to MTI
    - Delete ABC
    """
    dependencies = [
        ('core', '0009_course'),
    ]

    operations = [
        migrations.RunPython(forward_course_abc_to_mti,
                             backward_course_abc_to_mti)
    ]
